inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/colt'
    - 'vendor/**/*'
  NewCops: enable

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'lib/choria/colt/cli.rb'

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*_spec.rb'
