AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
  NewCops: enable

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 17

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*_spec.rb'
